name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: pnpm install

      - run: pnpm run version

      - run: git config user.name "github-actions[bot]"

      - run: git config user.email "github-actions[bot]@users.noreply.github.com"

      - run: git add .

      - name: Commit changes
        run: |
          git diff --cached --exit-code || git commit -m "ci: version bump"

      - run: git push

      - run: pnpm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}




# name: Release

# on:
#   push:
#     branches: [main]

# permissions:
#   contents: write 
#   pull-requests: write
#   packages: write



# jobs:
#   release:
#     name: Publish changed packages
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           registry-url: "https://registry.npmjs.org"

#       - name: Install pnpm
#         uses: pnpm/action-setup@v2
#         with:
#           version: 8

#       - name: Install dependencies
#         run: pnpm install

#       - name: Set up GitHub token
#         env:
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
#         run: |
#           git config --global user.name "github-actions[bot]"
#           git config --global user.email "github-actions[bot]@users.noreply.github.com"
#           git config --global --add safe.directory /home/runner/work/${{ github.event.repository.name }}
#           git config --global --add safe.directory /home/runner/work/${{ github.event.repository.name }}/packages/*

#       - name: Create release PR or publish
#         uses: changesets/action@v1
#         with:
#           publish: pnpm release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GH_TOKEN  }}  
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
